const mongoose = require('mongoose');

// A LinkCode is generated by one user and shared (however they like — text,
// WhatsApp, in person) with someone they trust. Whoever redeems it becomes
// linked to the user who generated it. Single-use, short-lived by design —
// this is a pairing code, not a permanent secret.
const linkCodeSchema = new mongoose.Schema({
  code: { type: String, required: true, unique: true, index: true },
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  expiresAt: { type: Date, required: true },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('LinkCode', linkCodeSchema);